books/urls.py
from django.urls import path
from .views import *

app_name = 'books'

urlpatterns = [
    path('',allbooks,name = 'allbooks'),
    path('<int:id>/',onebook,name = 'onebook'),
    path('upload/', upload, name= 'upload'),
]

projectTest/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home, name = 'home'),
    path('books/',include('books.urls')),
    path('users/',include('users.urls')),
]

urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('',createUser, name='create'),
    path('login/',login_user, name='login'),
    path('logout/',logout_user, name='logout'),
]

books/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length = 50,null = False, blank = False, unique = True)
    author = models.CharField(max_length = 100,null = False, blank = False)
    description = models.TextField(null = False, blank = False)
    price = models.FloatField(null = False, blank = False)
    pub_date = models.DateField()
    banner = models.ImageField(default = 'default.jpg', null = True, blank = True)
    def __str__(self):
        return self.title

users/models.py
from django.db import models
# Create your models here.

books/forms.py
from django.forms import ModelForm 
from .models import Book
from django import forms

class Form(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title','description','price','pub_date','banner']

users/forms.py
from django import forms
from django.contrib.auth.models import User

class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields ='__all__'

class LoginForm(forms.Form):
    username = forms.CharField(max_length=10,strip=True, required=True)
    password = forms.CharField(max_length=10,strip=True, required=True,
    widget=forms.PasswordInput(attrs={'input_type':'password'})
    )
    class Meta:
        model = User
        fields =['username','password']

books/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Book
from .forms import Form
from django.contrib.auth.decorators import login_required
@login_required(login_url = 'users:login')
def allbooks(request):
    books = Book.objects.all()
    return render(request, 'books/books.html',{ 'books':books })

@login_required(login_url = 'users:login')
def onebook(request, id):
    book = Book.objects.get(id=id)
    return render(request, 'books/book.html',{ 'book': book })


@login_required(login_url = 'users:login')


def upload(request):
    if request.method == 'POST':
        form = Form(request.POST, request.FILES)

        if form.is_valid():
            title = form.cleaned_data['title']
            pub_date = form.cleaned_data['pub_date']
            price = form.cleaned_data['price']
            description = form.cleaned_data['description']
            banner = request.FILES.get('banner')
            
            # Assuming you have a ForeignKey relationship between Book and User model
            if request.user.is_authenticated:
                author = request.user  # Use the authenticated user as the author
            else:
                author = None  # If user is not authenticated, set author to None or handle differently
            
            new_book = Book.objects.create(
                title=title,
                author=author,
                pub_date=pub_date,
                price=price,
                description=description,
                banner=banner,
            )
            print('Book saved successfully')
            return redirect('books:allbooks')
        else:
            print('Form is not valid:', form.errors)
    else:
        form = Form()
    

    print(request.user.get_full_name() ,'h')

    return render(request, 'books/upload.html',{  'form':form})

projectTest/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib import admin

def home(request):
    return render(request, 'main/index.html')

    

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse
from .forms import UserCreateForm,LoginForm

# Create your views here.
def createUser(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        if password != confirm_password:
            render(request,'users/create.html')
        else:
            user_vel=User.objects.filter(username = username).exists()
            if user_vel:
                render(request,'users/create.html')
            else:
                user = User.objects.create_user(username=username, email=email, password=password)
                user.first_name = firstname
                user.last_name = lastname
                user.save()
                return HttpResponse('new user created')
            print(username,password)
    return render(request,'users/create.html')

def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user_check = User.objects.filter(username = username).exists()
            if user_check:
                user = authenticate(request, username = username, password = password )

                if user is not None:
                    login(request,user)
                    return redirect('books:allbooks')
                else:
                    return render(request,'users/login.html',{'form':form})
            else:
                return render(request,'users/login.html',{'form':form})
        else:
            return render(request,'users/login.html',{'form':form})
    else:
        form = LoginForm()
        return render(request,'users/login.html',{'form':form})
def logout_user(request):
    logout(request)
    return redirect('users:login')

templates/books/book.html
{% extends "main/layout.html" %}
{% load  static %}

{% block title %}
    library | {{book.title}}
{% endblock title %}

{% block body %}
    <section class='onebook'>
        <div class="book">
            <h1>{{book.title}}</h1>
            <div class="img">
                <img src="{{ book.banner.url }}" alt="{{book.title}}">
            </div>
            <p class='desc'><b>Desc:</b><br> {{book.description}}</p>
            <p class='author'><b>Writen by:</b> {{book.author}}</p>
            <p class='price'><b>Published At:</b> {{book.pub_date}}</p>
            <p class='price'><b>Price:</b> {{ book.price }}</p>
        </div>
    </section> 
{% endblock body %}

templates/books/books.html
{% extends "main/layout.html" %}
{% load  static %}

{% block title %}
    library | books
{% endblock title %}

{% block body %}
    <h1>this is a list of all books</h1>
    <section>
        <div class="allbooks">
        {% for book in books %}
        <a href="{% url 'books:onebook' book.id%}">
            <article>
                <div class="img">
                    <img src="{{ book.banner.url }}" alt="{{book.title}}">
                </div>
                <p class='title'>Title: {{book.title}}</p>
                <p>Author: {{book.author}}</p>
                <p>Price: {{ book.price }}</p>
            </article>
        </a>
        {% endfor %}
        </div>
    </section>
{% endblock body %}

templates/books/upload.html
{% extends "main/layout.html" %}

{% block title %}
    submit form
{% endblock title %}

{% block body %}
    <div class=form_cont>
        <div  class='form'>
            <h2>Book Details</h2>
            <form action="{% url 'books:upload' %}" method="post" enctype='multipart/form-data'>
                {% csrf_token %}
                {{ form }}
                <button>save</button>
            </form>
        </div>
        <form action="" method="post"></form>
    </div>
{% endblock body %} 

templates/main/index.html
{% extends "main/layout.html" %}
{% load static %}
{% block title %}
    Library | Home
{% endblock title %}

{% block body %}
    <h1>this is the home page</h1>
    <img src="media\home.jpg" alt="">
{% endblock body %}

templates/main/layout.html
<!DOCTYPE html>
{% load  static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Library
        {% endblock title %}
    </title>
    <style>
        * {
  padding: 0;
  margin: 0;
  font-family: chillax;
  box-sizing: border-box;
}

body {
  height: 100%;
  width: 100%;
  background-color: #ffffff;
  overflow-x: hidden;
}

nav {
  height: 70px;
  width: 100vw;
  display: flex;
  align-items: center;
  justify-content: space-evenly;
  background-color: #454545;
}

li {
  display: inline;
}

li a {
  padding: 5px;
  text-decoration: none;
  color: black;
  background-color: white;
  font-size: 30px;
  border-radius: 5px;
}

nav h1 {
  text-transform: uppercase;
  color: #ffffff;
}

main h1 {
  text-transform: uppercase;
  text-align: center;
}

main section .allbooks {
  width: -moz-fit-content;
  width: fit-content;
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
  margin: auto;
  background-color: #000000;
}

main .allbooks article {
  padding: 10px;
  margin: 40px 0 0 40px;
  background-color: white;
  transition: all 0.3s;
  max-width: max(content);
}

main .all article:hover {
  box-shadow: 3px 3px 6px #454545;
}

main .allbooks article img {
  width: 50vh;
  height: 40vh;
}

main .allbooks article p {
  font-size: large;
  font-weight: 600;
}

main .allbooks article p.title {
  font-size: larger;
  font-weight: 700;
}

main .allbooks a {
  text-decoration: none;
  color: black;
}

section.onebook {
  background-color: rgb(0, 0, 0);
  height: -moz-fit-content;
  height: fit-content;
}

div.book {
  width: 50%;
  background-color: #dadada;
  margin: auto;
  padding: 10px;
  font-weight: 500;
  font-size: larger;
}

div.book img {
  height: 50%;
  margin-bottom: 20px;
  width: 100%;
}

div.book h1 {
  line-height: 60px;
  font-size: 30px;
}

div.book p {
  margin-top: 15px;
}

div.book p.desc {
  font-size: larger;
}

div.img {
  width: 100%;
}

.form_cont {
  width: 100%;
  display: flex;
  justify-content: center;
  padding-top: 20px;
}
.form_cont .form {
  background-color: #454545;
  padding: 10px;
}
.form_cont .form input {
  width: 99%;
  height: 35px;
  border: none;
  outline-color: gray;
  margin: 3px 10px 3px 3px;
  border-radius: 5px;
  padding: 3px;
}
.form_cont .form textarea {
  width: 99%;
  height: 215px;
  border: none;
  outline-color: gray;
  margin: 3px 10px 3px 3px;
  border-radius: 5px;
  resize: vertical;
}
.form_cont .form button {
  height: 30px;
  width: 70px;
  font-size: large;
  font-weight: 500;
  text-transform: capitalize;
  border: none;
  border-radius: 5px;
}
.form_cont .form h2 {
  text-align: center;
}
.form_cont .form label {
  font-size: large;
  font-weight: 500;
}/*# sourceMappingURL=styles.css.map */
    </style>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <nav>
        <div>
            <h1>library</h1>
        </div>
        <ul>
            <li><a href="{% url 'home'%}">🏠</a></li>
            <li><a href="{% url 'books:allbooks'%}">📚</a></li>
            <li><a href="{% url 'books:upload'%}">➕</a></li>
        </ul>
        {% if  request.user.is_authenticated%}
        <a href="{% url 'users:logout' %}">📤</a>
        {% endif %}
    </nav>
    <main>
        {% block body %}
        
        {% endblock body %}
    </main>
</body>
</html>

templates/users/create.html
{% extends "main/layout.html" %} {% block title %} create a user {% endblock title %} 

{% block body %}
<div class="form_cont">
  <div class="form">
    <h2>Book Details</h2>
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
      <div>
        <label for="username">user name</label>
        <input type="text" name="username" />
      </div>
        <div>
        <label for="email">email</label>
        <input type="email" name="email" />
      </div>
      <div>
        <label for="firstname">first name</label>
        <input type="text" name="firstname" />
      </div>
      <div>
        <label for="lastname">last name</label>
        <input type="text" name="lastname" />
      </div>
      
      <div>
          <label for="password">password</label>
          <input type="password" name="password" />
        </div>
        <div>
          <label for="confirm_password">confirm Password</label>
          <input type="password" name="confirm_password" />
        </div>
        <button>save</button>
    </form>
  </div>
</div>
{% endblock body %}

templates/users/login.html
{% extends "main/layout.html" %} {% block title %} create a user {% endblock title %} 

{% block body %}
<div class="form_cont">
  <div class="form">
    <h2>Book Details</h2>
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
      
        {{form}}
        <button>save</button>
    </form>
  </div>
</div>
{% endblock body %}